Algoritmo "A+1"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nathalia Alves Silva
// Data atual  : 14/09/2021
Var
// Seção de Declarações das variáveis 

   a, b : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   a <- 10
   b <- a + 1
   a <- b + 1
   b <- a + 1

   escreval(a)
   
   a <- b + 1
   
   escreval(a, b)
   
Fimalgoritmo