Algoritmo "ABeC"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nathalia Alves Silva
// Data atual  : 14/09/2021
Var
// Seção de Declarações das variáveis 

   a, b, c : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

    a <- 30
    b <- 20
    c <- a + b
    
    escreval(c)
    
    b <- 10
    
    escreval(b, c)
    
    c <- a + b
    
    escreval(a, b, c)




Fimalgoritmo