Algoritmo "Algoritmo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nathalia Alves Silva
// Data atual  : 15/09/2021
Var
// Seção de Declarações das variáveis 

  z, A, B, C : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   z <- (50*3) + 5
   
   se z <= 0 então
      escreval("A")
   senão
   se z <= 100 então
      escreval("B")
      senão
      escreval("C")
      fimse
      fimse


Fimalgoritmo