Algoritmo "OlaSofisticado"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nathalia Alves Silva
// Data atual  : 22/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
// Um retangulo feito com qualquer item


   escreval("########################")
   escreval("##### OLA MUNDO! #######")
   escreval("########################")

Fimalgoritmo