Algoritmo "SemAlterarResultado"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nathalia Alves Silva
// Data atual  : 15/09/2021
Var
// Seção de Declarações das variáveis 

   a, b, c, d : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   a <- 6*5
   escreval(a)
   
   b <- 2+6*5
   escreval(b)
   
   c <- 2+(3*6)/(2+4)
   escreval(c)
   
   d <- 2*8/(3+1)
   escreval(d)
   
Fimalgoritmo