Algoritmo "xyz"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nathalia Alves Silva
// Data atual  : 14/09/2021
Var
// Seção de Declarações das variáveis 

   x, y, z : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   x <- 1
   y <- 2
   z <- y - x
   
   escreval(z)
   
   x <- 5
   y <- x + z
   
   escreval(x, y, z)


Fimalgoritmo